apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: proxmox-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-backend
  target:
    name: proxmox-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PVE_USER: "{{ .pveuser }}"
        PVE_TOKEN_NAME: "{{ .pvetokenname }}"
        PVE_TOKEN_VALUE: "{{ .pvetokenvalue }}"
  data:
    - secretKey: pveuser
      remoteRef:
        key: proxmox-api-token-prom-exporter-user
    - secretKey: pvetokenname
      remoteRef:
        key: proxmox-api-token-prom-exporter-name
    - secretKey: pvetokenvalue
      remoteRef:
        key: proxmox-api-token-prom-exporter-value
