apiVersion: v1
kind: Service
metadata:
  name: prometheus-pve-exporter
  namespace: monitoring
  labels:
    app: prometheus-pve-exporter
    app.kubernetes.io/name: prometheus-pve-exporter
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9221
      targetPort: 9221
      protocol: TCP
  selector:
    app: prometheus-pve-exporter
