apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wg-easy
  namespace: wg-easy
  labels:
    app.kubernetes.io/name: wg-easy
    app.kubernetes.io/component: vpn
    app.kubernetes.io/managed-by: kustomize
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
  - host: wireguard.krebiehl.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wg-easy
            port:
              number: 51821
  tls:
  - hosts:
    - wireguard.krebiehl.com
    secretName: wg-easy-tls
