apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomizations
  dependsOn:
    - name: cert-manager
    - name: traefik
    - name: proxmox-csi-plugin
