apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-ks.yaml
  - external-dns-ks.yaml
  - metallb-ks.yaml
  - metallb-address-pool-ks.yaml
  - traefik-ks.yaml
  - external-secrets-ks.yaml
  - azure-secret-store-ks.yaml
  - cert-manager-issuer-ks.yaml
