apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-pve-exporter
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/prometheus-pve-exporter
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomizations
  dependsOn:
    - name: kube-prometheus-stack
    - name: external-secrets
