apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-kustomizations
  dependsOn:
    - name: metallb
    - name: cert-manager
